server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_subscriber?serverTimezone=UTC
    username: alex
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create